package com.example.plantDetector;

public class Classes {
    public static String[] IMAGE_CLASSES = new String[]{
            "Apple___Apple_scab",
            "Apple___Black_rot",
            "Apple___Cedar_apple_rust",
            "Apple___healthy",
            "Blueberry___healthy",
            "Cherry_(including_sour)___Powdery_mildew",
            "Cherry_(including_sour)___healthy",
            "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
            "Corn_(maize)___Common_rust_",
            "Corn_(maize)___Northern_Leaf_Blight",
            "Corn_(maize)___healthy",
            "Grape___Black_rot",
            "Grape___Esca_(Black_Measles)",
            "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
            "Grape___healthy",
            "Orange___Haunglongbing_(Citrus_greening)",
            "Peach___Bacterial_spot",
            "Peach___healthy",
            "Pepper,_bell___Bacterial_spot",
            "Pepper,_bell___healthy",
            "Potato___Early_blight",
            "Potato___Late_blight",
            "Potato___healthy",
            "Raspberry___healthy",
            "Soybean___healthy",
            "Squash___Powdery_mildew",
            "Strawberry___Leaf_scorch",
            "Strawberry___healthy",
            "Tomato___Bacterial_spot",
            "Tomato___Early_blight",
            "Tomato___Late_blight",
            "Tomato___Leaf_Mold",
            "Tomato___Septoria_leaf_spot",
            "Tomato___Spider_mites Two-spotted_spider_mite",
            "Tomato___Target_Spot",
            "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
            "Tomato___Tomato_mosaic_virus",
            "Tomato___healthy"
    };

    public static String[] PLANT_NAMES = new String[] {
        "Яблоня",
        "Яблоня",
        "Яблоня",
        "Яблоня",
        "Черника",
        "Вишня",
        "Вишня",
        "Кукуруза",
        "Кукуруза",
        "Кукуруза",
        "Кукуруза",
        "Виноград",
        "Виноград",
        "Виноград",
        "Виноград",
        "Апельсин",
        "Персик",
        "Персик",
        "Красный перец",
        "Красный перец",
        "Картофель",
        "Картофель",
        "Картофель",
        "Малина",
        "Соя",
        "Кабачок",
        "Земляника",
        "Земляника",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат",
        "Томат"
    };

    public static String[] DISEASE_NAMES = new String[] {
        "Парша",
        "Черная гниль",
        "Ржавчина",
        "Здоровый",
        "Здоровый",
        "Мучнистая плесень",
        "Здоровый",
        "Серая листовая пятнистость",
        "Обыкновенная ржавчина",
        "Поражение(ожог) листьев",
        "Здоровый",
        "Черная гниль",
        "Поражение листьев(черные мозоли)",
        "Поражение листьев",
        "Здоровый",
        "Позеленение плодов цитрусов",
        "Бактериальная пятнистость",
        "Здоровый",
        "Бактериальная пятнистость",
        "Здоровый",
        "Раннее поражение листьев",
        "Позднее(сильное) поражение листьев",
        "Здоровый",
        "Здоровый",
        "Здоровый",
        "Мучнистая роса",
        "Ожог листьев",
        "Здоровый",
        "Бактериальная пятнистость",
        "Раннее поражение листьев",
        "Позднее(сильное) поражение листьев",
        "Листовая плесень",
        "Септориозная листовая пятнистость",
        "Паутинный клещ",
        "Точечная пятнистость",
        "Вирус желтой курчавости листьев",
        "Вирус мозаики",
        "Здоровый"
    };

}
